### ISSUE TITLE
add a feature for configurable card size

### ISSUE THREAD

**Issue by tgaochn** [NBKRedSpy/CardSurvival-ViewMoreCards#2]
Is there any plan to add a config file and make the card size configurable?
Thanks!

**Comment by NBKRedSpy** [comment]
Also, are the changes too large or too small?  I chose about 60% size since it was a decent balance between text readability and more visible cards.

**Comment by tgaochn** [comment]
The current size is a little bit large for me. I would try 40% if get the chance.

**Comment by NBKRedSpy** [comment]
Closing with correct close reason.

**Comment by NBKRedSpy** [comment]
If you haven't seen it already, checkout the "Add Hand Slot" mod on Nexus Mods.  It supports double lines of cards which I think is about the size you are looking for.

https://www.nexusmods.com/cardsurvivaltropicalisland/mods/94

**Comment by tgaochn** [comment]
Thanks a lot for the update!
